### PR TITLE
feat: Expose Verifier- and SignerAlgorithm

### PR DESCRIPTION
**Pull request by oed**
Need the Verifier- and SignerAlgorithm separately. This PR exposes them in the exports.

### CODE REVIEW

**Comment by mirceanis** [comment]
What is the purpose of this?
Those are internal implementations.
I'm not sure this should become public API, since it can't receive any support.

**Comment by oed** [comment]
I basically want the ability to sign messages without encoding the data as a JWT format. It seems unlikely that these implementations will change, so I don't see any harm in exposing them. 

Most basically I want to be able to verify a signature without resolving a DID. I guess an option to pass an `authenticators` object to verifyJWT could also work.

**Comment by mirceanis** [comment]
Even with the verifier alg exposed, you still need to construct a list of `authenticators` to pass around.
`verifyJWT` does not take that as a parameter.
What is the API you are looking to call?

It is not only about potentially changing the internal methods. Having this exposed here means we would have to provide similar methods on other platforms. The implementations there are completely different.

**Comment by mi-xu** [comment]
@oed If you want to sign messages and verify those signatures without doing anything involving JWTs then does it make sense to do that through this library?  What about just using secp256k1 from the Elliptic module instead?

**Comment by oed** [comment]
Managed to solve it by just taking the signature part of the JWT, then reconstructing the header + payload when verifying. 
My use case is basically that I already have the data that I'm signing in the data structure and just want to add a proof. So it doesn't make sense to also store the JWT payload.

**Pull request closed without merging**
